# This is a basic workflow to help you get started with Actions

name: Pull Request build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    - name: Compile common-lib
      run: |
        cd $GITHUB_WORKSPACE/common-lib
        yarn install
        yarn build
    - name: Compile Server
      run: |
        cd $GITHUB_WORKSPACE/server
        yarn install
        yarn build-ts
    - name: Compile Angular
      run: |
        cd $GITHUB_WORKSPACE/client
        yarn install
        yarn build
