name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    - name: Compile common-lib
      run: |
        cd $GITHUB_WORKSPACE/common-lib
        yarn install
        yarn build
    - name: Compile Server
      run: |
        cd $GITHUB_WORKSPACE/server
        yarn install
        yarn build-ts
    - name: Push server docker-image
      run: |
        cd $GITHUB_WORKSPACE/server
        yarn install --prod
        echo "TAG: ${GITHUB_REF##*/}"
        docker build . -t robertschreib/maiern-server:${GITHUB_REF##*/}
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push robertschreib/maiern-server:${GITHUB_REF##*/}
    - name: Compile Angular
      run: |
        cd $GITHUB_WORKSPACE/client
        yarn install
        yarn build
    - name: Push client docker-image
      run: |
        cd $GITHUB_WORKSPACE/client
        echo "TAG: ${GITHUB_REF##*/}"
        docker build . -t robertschreib/maiern-client:${GITHUB_REF##*/}
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push robertschreib/maiern-client:${GITHUB_REF##*/}
        
